function writeoutput(s::AbstractSimulation,init::Integer)
  mycopy!(s.aux,s.u,s)
  irfft!(s.aux,s.pb,s)
  write("u1.$init",s.aux.rx)
  write("u2.$init",s.aux.ry)
  write("u3.$init",s.aux.rz)
  dealias!(s.aux,s)
  if haspassivescalar(s)
    copy!(parent(real(s.passivescalar.ρrhs)),parent(real(s.passivescalar.ρ)))
    irfft!(s.passivescalar.ρrhs,s.passivescalar.pbs,s)
    write("scalar.$init",s.passivescalar.ρrhs)
    dealias!(s.passivescalar.ρrhs,s)
  end
  if hasdensity(s)
    copy!(parent(real(s.densitystratification.ρrhs)),parent(real(s.densitystratification.ρ)))
    irfft!(s.densitystratification.ρrhs,s.densitystratification.pbs,s)
    write("rho.$init",s.densitystratification.ρrhs)
    dealias!(s.densitystratification.ρrhs,s)
  end
end
